package com.lab.dao;

import com.lab.model.TimeSlot;
import com.lab.util.DBConnection;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class TimeSlotDAO {

    // 1. Method untuk tarik slot yang available ikut Station & Tarikh
    public List<TimeSlot> getSlotsByStationAndDate(String stationId, String date) {
        // Tarik data dari database dulu
        List<TimeSlot> list = fetchSlotsFromDB(stationId, date);
        
        // AUTO-GENERATOR MAGIC: Jika list kosong (belum ada slot utk tarikh ni), generate!
        if (list.isEmpty()) {
            autoGenerateDailySlots(stationId, date);
            list = fetchSlotsFromDB(stationId, date); // Tarik semula lepas generate
        }
        return list;
    }

    // Helper Method 1: Tarik data dari DB (Code asal kau)
    private List<TimeSlot> fetchSlotsFromDB(String stationId, String date) {
        List<TimeSlot> list = new ArrayList<>();
        // Kita check is_available = 1 supaya tak tunjuk slot yang dah kena book
        String query = "SELECT * FROM time_slot WHERE station_id = ? AND slot_date = ? AND is_available = 1 ORDER BY start_time ASC";
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {
            
            stmt.setString(1, stationId);
            stmt.setString(2, date);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                TimeSlot ts = new TimeSlot();
                ts.setSlotId(rs.getString("slot_id"));
                ts.setStationId(rs.getString("station_id"));
                ts.setSlotDate(rs.getDate("slot_date"));
                ts.setStartTime(rs.getTime("start_time"));
                ts.setEndTime(rs.getTime("end_time"));
                ts.setIsAvailable(rs.getInt("is_available"));
                list.add(ts);
            }
        } catch (SQLException e) {
            System.err.println("Error fetching slots: " + e.getMessage());
            e.printStackTrace();
        }
        return list;
    }

    // Helper Method 2: The Auto-Generator (Using Arrays and Loops)
    private void autoGenerateDailySlots(String stationId, String date) {
        // Kita tetapkan 5 slot standard (2-jam) setiap hari guna Array
        String[] startTimes = {"10:00:00", "12:00:00", "14:00:00", "16:00:00", "20:00:00"};
        String[] endTimes =   {"12:00:00", "14:00:00", "16:00:00", "18:00:00", "22:00:00"};
        
        String query = "INSERT INTO time_slot (slot_id, station_id, slot_date, start_time, end_time, is_available) VALUES (?, ?, ?, ?, ?, 1)";
        
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(query)) {
            
            // Loop melalui array untuk cipta 5 slot secara automatik
            for (int i = 0; i < startTimes.length; i++) {
                String uniqueSlotId = "SLOT-" + UUID.randomUUID().toString().substring(0, 6).toUpperCase();
                
                ps.setString(1, uniqueSlotId);
                ps.setString(2, stationId);
                ps.setDate(3, Date.valueOf(date));
                ps.setTime(4, Time.valueOf(startTimes[i]));
                ps.setTime(5, Time.valueOf(endTimes[i]));
                ps.addBatch(); // Masukkan dalam queue (batch processing)
            }
            
            ps.executeBatch(); // Execute semua query serentak ke dalam MySQL!
            System.out.println("DEBUG: Auto-generated 5 new slots for station " + stationId + " on " + date);
            
        } catch (SQLException e) { 
            e.printStackTrace(); 
        }
    }

    // 2. Method untuk update status slot (Guna masa student dah setel booking)
    public boolean updateSlotAvailability(String slotId, int status) {
        String query = "UPDATE time_slot SET is_available = ? WHERE slot_id = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {
            
            stmt.setInt(1, status); // 0 = Taken, 1 = Available
            stmt.setString(2, slotId);
            
            return stmt.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
}